

logging:
  config: classpath:logback.xml
spring:
    zipkin:
        baseUrl: http://localhost:9411
        enabled: true
    sleuth: 
        sampler:
            percentage: 1.0
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    datasource:
        url: jdbc:mysql://118.178.227.169:3306/ntsc_wechatcampus
        username: stest
        password: test
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        timeout: 0
        pool:
                max-active: 8
                max-wait: -1
                min-idle: 0

mybatis:
    type-aliases-package: cn.edu.ntsc.job.domain
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql